### ISSUE TITLE
Compilation can't be completed because some library classes are missing.

### ISSUE THREAD

**Issue by SABlyu** [vmwareairwatchsdk/vmware-ws1-sdk-forms#1]
> R8 : warning : Missing class: org.apache.http.impl.client.DefaultHttpClient
> R8 : warning : Missing class: org.apache.http.auth.AuthSchemeFactory
> R8 : warning : Missing class: org.eclipse.jetty.npn.NextProtoNego$ClientProvider
> R8 : warning : Missing class: org.jboss.marshalling.ByteOutput
> R8 : warning : Missing class: org.apache.tomcat.jni.CertificateVerifier
> R8 : warning : Missing class: java.lang.ClassValue
> R8 : warning : Missing class: org.apache.tomcat.jni.CertificateRequestedCallback
> R8 : warning : Missing class: org.eclipse.jetty.alpn.ALPN$ClientProvider
> R8 : warning : Missing class: org.jboss.marshalling.ByteInput
> R8 : warning : Missing class: org.apache.http.conn.routing.HttpRoutePlanner
> R8 : warning : Missing class: org.eclipse.jetty.npn.NextProtoNego$ServerProvider
> R8 : warning : Missing class: org.apache.http.auth.AuthScheme
> R8 : warning : Missing class: org.eclipse.jetty.alpn.ALPN$ServerProvider
> R8 : warning : Missing class: org.apache.http.HttpRequestInterceptor
> R8 : warning : Missing class: com.sun.nio.sctp.AbstractNotificationHandler
> R8 : error : Compilation can't be completed because some library classes are missing.

guys, any chance I can resolve these anyhow?

**Comment by Maddy79** [comment]
@SABlyu , which VS version are you using. VS 8.4 for Mac the app builds issue is seen with 8.5.
Please refer the below bug reported with MS.
https://github.com/xamarin/xamarin-android/issues/3444#issuecomment-535049639

Also if you can use Xamarin.Android 10.1, it should build. We have build the app using https://appcenter.ms/

**Comment by Maddy79** [comment]
With latest VS build this issue is fixed.
