### ISSUE TITLE
How to detect if device is currently under mdm control?

### ISSUE THREAD

**Issue by danlfarnell** [vmwareairwatchsdk/vmware-ws1-sdk-forms#16]
Hi,

I just had a question. I was wondering how you would detect if a device is currently under the control of AirWatch?  Any sample code you can provide or url to references would be most appreciated.  Thanks in advance.

**Comment by akalghatgi** [comment]
Hi @danlfarnell 
      Once you Start/Init the WS1SDK you should get a Delegate. Call back if the Device Enrollment status. Following is the code snippet. 

void IAWSDKDelegate.EnrollmentStatusReceived(object status)
        {

        }

You can find the reference of Delegate method [here](https://github.com/vmwareairwatchsdk/vmware-ws1-sdk-forms/blob/master/WorkspaceOne.Example/App.xaml.cs)

Regards,
Amit

**Comment by danlfarnell** [comment]
Hi,

Thank you very much for your response!!
