### ISSUE TITLE
Custom Settings Payload is always null on Android

### ISSUE THREAD

**Issue by bengibagci** [vmwareairwatchsdk/vmware-ws1-sdk-forms#21]
Hi,

I can't get _Custom Settings Payload_ this way: 
`App.Profiles.FirstOrDefault(p => p.ProfileType == WorkspaceOne.Forms.AWProfileType.SDKProfile)?.CustomPayload;`  

But when I use SDKManager independent from WorkspaceOne.Forms as below, I can get Custom Setting Payload:
(OnActivityResumed method in MainApplication)

![sdkmanager](https://user-images.githubusercontent.com/39203037/201291123-c4810133-fd56-47c1-97fd-0a5ad1248bd1.png)

I don't want to make different solution for iOS and Android. Please, update WorkspaceOne.Forms.

**Comment by Pelinalpp** [comment]
I am also having the same problem. Could you publish WorkspaceOne.Forms library as open source to the github? If you do, we will try to fixed it.

**Comment by akalghatgi** [comment]
@Pelinalpp @bengibagci 
Kindly use [this](https://github.com/vmwareairwatchsdk/vmware-ws1-sdk-forms/blob/master/WorkspaceOne.Example/Pages/RemoteConfigPage.xaml.cs) approach to get CustomPayload.
