### ISSUE TITLE
Maui support question

### ISSUE THREAD

**Issue by danlfarnell** [vmwareairwatchsdk/vmware-ws1-sdk-forms#25]
Hi,  

End of Life for Xamarin will be May 1, 2024.  Is there any plans to build a Maui compatible Sdk in the works?  If so, do you have a rough Eta?  Thanks in advance.

**Comment by Maddy79** [comment]
Thanks @danlfarnell  for bringing this up, we will be working on the migration efforts by mid 2023, with a beta release around that timeframe.

**Comment by danlfarnell** [comment]
Thanks @Maddy79.  Appreciate it. :)
